### ISSUE TITLE
앱 UI 불일치

### ISSUE THREAD

**Issue by Jinho1011** [sullog-official/sullog-client#182]
1. 술 검색 input 밀림
<img width="608" alt="image" src="https://github.com/sullog-official/sullog-client/assets/26860466/07f0c2f3-d26f-49b2-a0ee-92d303db3c53">
<img width="608" alt="image" src="https://github.com/sullog-official/sullog-client/assets/26860466/a02c0624-e3a7-4414-b98a-2679a8b68fa0">

2. 앱 확대가 가능함
<img width="608" alt="image" src="https://github.com/sullog-official/sullog-client/assets/26860466/6e426851-3774-4bd8-9bce-f70cf699f9e6">

3. 상단 헤더가 뚫림
<img width="608" alt="image" src="https://github.com/sullog-official/sullog-client/assets/26860466/20335361-eddc-4086-8dcd-42eee9f661e3">

4. 주종 필터 중앙정렬 안됨
<img width="608" alt="image" src="https://github.com/sullog-official/sullog-client/assets/26860466/12caa88a-7bf3-4dbd-9dc2-2f5da0d94512">

**Comment by shinwonse** [comment]
input이 밀린다는거는 위에서부터 너무 내려와있어서 ui가 가려진다는거죠?

**Comment by Jinho1011** [comment]
> input이 밀린다는거는 위에서부터 너무 내려와있어서 ui가 가려진다는거죠?

input이 충분한 높이를 확보하지 못해 밑에 있는 내용물들이 올라오는거 같아요

**Comment by syoung125** [comment]
1,3이 같은 에러 같네요ㅠ
